source 'https://rubygems.org'
ruby '2.5.1'

gem 'byebug'
gem 'capybara'
gem 'capybara-screenshot'
gem 'chilkat'
gem 'chunky_png', '1.3.7'
gem 'cucumber', '3.1.2'
gem 'cuke_sniffer'
gem 'data_magic'
gem 'dotenv'
gem 'faker'
gem 'foreman', '~> 0.87.2'
gem 'imatcher', '0.1.5'
gem 'os'
gem 'parallel_tests'
gem 'pdf-reader'
gem 'pry'
gem 'pry-byebug'
gem 'report_builder'
gem 'require_all'
gem 'rspec', '~> 3.5'
gem 'rspec-expectations', '3.5.0'
gem 'rubocop', '0.59.2', require: false
# gem 'selenium-webdriver'
gem 'show_me_the_cookies'
gem 'site_prism'
gem 'site_prism-table'
gem 'touch_action'
gem 'selenium-webdriver', '4.0.0.alpha1'
